# Config file for the acts_as_cleo plugin.
development:
  url: "http://localhost:8080/cleo-primer/"

test:
  url: "http://localhost:8080/cleo-primer/"

production:
  url: "http://localhost:8080/cleo-primer/"
  run_async: true
  queue: "cleo"
