# Config file for the acts_as_solr plugin.
#
# If you change the host or port number here, make sure you update
# them in your Solr config file

development:
  url: "http://cleo.neighborhoods.com/cleo-primer/rest/elements/"

production:
  url: "http://cleo.neighborhoods.com/cleo-primer/rest/elements/"
